import type { Service } from '../types'

// Seed data ported from the user's Notion price list CSV.
// purchasePrice = "Kosten (Netto)" — what it costs the company per unit
// salePrice     = "Rechnung (Netto)" — what the company charges per unit
//
// NOTE: categoryId is set to empty strings here because real category IDs
// are generated by the API seed endpoint. This seed data is only a fallback
// for offline/no-backend mode — in production, services come from the API
// with proper categoryId UUIDs.
//
// IMPORTANT: A few rows in the source CSV had outlier sale prices that look
// like data-entry mistakes (e.g. Briefpapier listed at 8.423,36 € for a single
// package). They are imported as-is so nothing is silently changed; review and
// fix them on the "Preisliste" page after first launch.

const now = Date.now()

function svc(
  id: string,
  name: string,
  categoryId: string,
  purchasePrice: number,
  salePrice: number,
  defaultQuantity = 1,
  url?: string,
  note?: string,
  visible = true,
): Service {
  return {
    id,
    name,
    categoryId,
    purchasePrice,
    salePrice,
    defaultQuantity,
    url,
    note,
    visible,
    createdAt: now,
    updatedAt: now,
  }
}

// Category IDs are empty strings — real UUIDs come from the API seed endpoint.
// The comments show which category each service belongs to for reference.
export const seedServices: Service[] = [
  // ─── Print & Marketing ───────────────────────────────
  svc(
    'seed-stempel',
    'Stempel',
    '',
    9.24,
    21.64,
    1,
    'https://www.vistaprint.de/einladungen-und-schreibwaren/personalisierte-stempel/selbstfaerbende-stempel',
    'Selbstfärbender Stempel',
  ),
  svc(
    'seed-visitenkarten-rund',
    'Visitenkarten (abgerundet)',
    '',
    0.08,
    71.01,
    250,
    'https://www.vistaprint.de/visitenkarten/abgerundete-ecken',
    'Abgerundete Ecken, Standardpapier',
  ),
  svc(
    'seed-visitenkarten',
    'Visitenkarten Standard',
    '',
    0.07,
    16.81,
    250,
    'https://www.vistaprint.de/visitenkarten/abgerundete-ecken',
  ),
  svc(
    'seed-flyer-ohne-falz',
    'Flyer ohne Falz (A5)',
    '',
    0.08,
    51.01,
    250,
    'https://www.vistaprint.de/marketingmaterial/flyer',
    'Format A5',
  ),
  svc(
    'seed-flyer-ohne-falz-500',
    'Flyer ohne Falz A5 (500)',
    '',
    0.07,
    67.22,
    500,
    'https://www.vistaprint.de/marketingmaterial/flyer',
  ),
  svc(
    'seed-flyer-einbruch',
    'Flyer mit Einbruchfalz',
    '',
    36.13,
    9085.61,
    250,
    'https://www.vistaprint.de/marketingmaterial/flyer',
    '198×99×210 mm',
  ),
  svc(
    'seed-flyer-wickel',
    'Flyer mit Wickelfalz',
    '',
    35.29,
    3574.41,
    100,
    'https://www.vistaprint.de/marketingmaterial/flyer',
    '297×99×210 mm',
  ),
  svc(
    'seed-flyer-zickzack',
    'Flyer mit Zickzackfalz',
    '',
    37.82,
    3826.51,
    100,
    'https://www.vistaprint.de/marketingmaterial/flyer',
    '297×99×210 mm',
  ),
  svc(
    'seed-briefpapier',
    'Briefpapier',
    '',
    33.61,
    8423.36,
    250,
    'https://www.vistaprint.de/einladungen-und-schreibwaren/briefpapier',
    '⚠ Sale price imported from CSV — bitte prüfen',
  ),
  svc(
    'seed-briefumschlag',
    'Briefumschläge',
    '',
    109.24,
    27325.92,
    250,
    'https://www.vistaprint.de/einladungen-und-schreibwaren/briefumschlaege',
    '⚠ Sale price imported from CSV — bitte prüfen',
  ),

  // ─── Werbeartikel ─────────────────────────────────────
  svc(
    'seed-kugelschreiber',
    'Kugelschreiber Premium',
    '',
    66.81,
    3355.34,
    50,
    'https://www.vistaprint.de/werbeartikel/schreib-buerobedarf/personalisierte-kugelschreiber/premium-kugelschreiber',
  ),
  svc(
    'seed-kugelschreiber-elite',
    'Kugelschreiber Elite Soft Touch',
    '',
    66.81,
    3355.34,
    50,
    'https://www.vistaprint.de/werbeartikel/schreib-buerobedarf/personalisierte-kugelschreiber/kugelschreiber-elite-soft-touch-schwarze-tinte',
  ),
  svc(
    'seed-jahresplaner',
    'Jahresplaner 2026',
    '',
    42.02,
    225.08,
    5,
    'https://www.vistaprint.de/fotogeschenke/fotokalender/jahresplaner-2026',
  ),

  // ─── POS Display ──────────────────────────────────────
  svc(
    'seed-dreieck',
    'Dreieck-Pappaufsteller',
    '',
    52.10,
    82.10,
    1,
    'https://www.vistaprint.de/werbetechnik/pos-displays/dreieck-pappaufsteller',
    '50 × 50 × 185 cm, 4 stapelbare Teile, 2,3 mm Wellpappe (E-Welle)',
  ),
  svc(
    'seed-bodenaufsteller',
    'Bodenaufsteller (vierseitig)',
    '',
    68.91,
    118.91,
    1,
    'https://www.vistaprint.de/werbetechnik/pos-displays/bodenaufsteller-vierseitig',
    '33 × 33 × 200 cm oder 70 × 70 × 200 cm',
  ),

  // ─── Web & Digital ────────────────────────────────────
  svc(
    'seed-website',
    'Website Design',
    '',
    0,
    252.0,
    1,
    undefined,
    'Komplette Website inkl. Design',
  ),
  svc(
    'seed-website-anpassung',
    'Website Anpassung',
    '',
    0,
    50.0,
    3,
    undefined,
    'Stundenbasis pro Anpassung',
  ),
  svc(
    'seed-logo',
    'Logo Design',
    '',
    0,
    50.0,
    1,
  ),
  svc(
    'seed-logo-variant',
    'Logo (Variante)',
    '',
    0,
    25.0,
    1,
  ),
  svc(
    'seed-social',
    'Social Media Post',
    '',
    0,
    60.0,
    4,
    undefined,
    'Pro Post inkl. Grafik',
  ),

  // ─── Hosting & Domains ────────────────────────────────
  svc(
    'seed-de-domain',
    'DE-Domain',
    '',
    12.61,
    12.61,
    1,
    undefined,
    '.de Domain pro Jahr',
  ),
  svc(
    'seed-com-domain',
    'COM-Domain',
    '',
    13.45,
    5.0,
    1,
    undefined,
    '.com Domain pro Jahr',
    false,
  ),
  svc(
    'seed-hosting',
    'Hosting',
    '',
    8.40,
    8.40,
    1,
    undefined,
    'Standard Webhosting',
  ),
  svc(
    'seed-mail',
    'Starter Business Email 10GB',
    '',
    19.33,
    39.33,
    1,
    undefined,
    'Pro Postfach / Jahr',
  ),
  svc(
    'seed-workspace',
    'Google Workspace (Starter)',
    '',
    72.27,
    104.03,
    1,
    undefined,
    'Pro User / Jahr',
  ),
]
